{{- if .Values.includeLegacyServices }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "renku.notebooks.fullname" . }}-options
  labels:
    app: {{ template "renku.notebooks.name" . }}
    chart: {{ template "renku.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  server_options.json: |
    {{ .Values.notebooks.serverOptions | default dict | toJson }}
  server_defaults.json: |
    {{ toJson .Values.notebooks.serverDefaults }}
{{- end }}
