# -*- coding: utf-8 -*-
#
# Copyright 2017, 2018 - Swiss Data Science Center (SDSC)
# A partnership between École Polytechnique Fédérale de Lausanne (EPFL) and
# Eidgenössische Technische Hochschule Zürich (ETHZ).
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

version: '3'
volumes:
  db-data: {}
  gitlab-config: {}
  gitlab-logs: {}
  gitlab-data: {}
  gitlab-runner-data: {}
services:
  db:
    image: postgres:9.6
    environment:
      PGDATA: /pgdata
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - ./services/postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
      - db-data:/pgdata
    networks:
      - default
    healthcheck:
      test: ["CMD", "sh", "-c", "exec pg_isready"]
      interval: 30s
      timeout: 5s
      retries: 6

  keycloak:
    build: ./services/keycloak
    environment:
      KEYCLOAK_MIGRATION_FILE: /data/renku-realm.json
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_USER: admin
      POSTGRES_DATABASE: keycloak
      POSTGRES_PASSWORD: keycloak
      POSTGRES_PORT_5432_TCP_ADDR: db
      POSTGRES_USER: keycloak
      RENKU_ENDPOINT: ${RENKU_ENDPOINT}
      GITLAB_URL: ${GITLAB_URL}
      RENKU_UI_URL: ${RENKU_UI_URL}
      GITLAB_CLIENT_SECRET: ${GITLAB_CLIENT_SECRET}
      JUPYTERHUB_URL: ${JUPYTERHUB_URL}
      JUPYTERHUB_CLIENT_SECRET: ${JUPYTERHUB_CLIENT_SECRET}
    command:
      - "-b 0.0.0.0"
      - "-Dkeycloak.migration.action=import"
      - "-Dkeycloak.migration.provider=singleFile"
      - "-Dkeycloak.migration.file=/data/renku-realm.json"
      - "-Dkeycloak.migration.strategy=IGNORE_EXISTING"
    restart: on-failure
    labels:
      traefik.enable: "true"
      traefik.frontend.rule: "Host:keycloak.${PLATFORM_DOMAIN}"
      traefik.frontend.entryPoints: "service, http"
      traefik.frontend.redirect.entryPoint: "service"
    depends_on:
      - db
    networks:
      default:
        aliases:
          - keycloak.${PLATFORM_DOMAIN}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/auth"]
      interval: 60s
      timeout: 30s
      retries: 5

  gitlab:
    image: gitlab/gitlab-ce:latest
    restart: always
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url '${GITLAB_URL}'
        registry_external_url '${GITLAB_REGISTRY_URL}'
        # Enable or disable automatic database migrations
        # gitlab_rails['auto_migrate'] = false
        # manually run: gitlab-ctl pg-upgrade
        # FIXME change from postgres to gitlab
        # TODO need to run gitlab-rake gitlab:setup for external db
        #postgresql['enable'] = false
        #gitlab_rails['db_username'] = 'postgres'
        #gitlab_rails['db_password'] = 'postgres'
        #gitlab_rails['db_host'] = 'db'
        #gitlab_rails['db_port'] = 5432
        #gitlab_rails['db_database'] = 'gitlab'
        #gitlab_rails['db_adapter'] = 'postgresql'
        #gitlab_rails['db_encoding'] = 'utf8'
        gitlab_rails['omniauth_enabled'] = true
        gitlab_rails['omniauth_auto_sign_in_with_provider'] = 'oauth2_generic'
        gitlab_rails['omniauth_allow_single_sign_on'] = ['oauth2_generic']
        gitlab_rails['omniauth_block_auto_created_users'] = false
        gitlab_rails['omniauth_providers'] = [
          {
            'name' => 'oauth2_generic',
            'app_id' => 'gitlab',
            'app_secret' => '${GITLAB_CLIENT_SECRET}',
            'args' => {
              client_options: {
                # Traefik maps keycloak to the URL below
                # CAREFUL: This must be accessible from inside the keycloak container
                # for service-to-service communication.
                'site' => '${KEYCLOAK_URL}/auth',
                'authorize_url' => '/auth/realms/Renku/protocol/openid-connect/auth',
                'user_info_url' => '/auth/realms/Renku/protocol/openid-connect/userinfo',
                'token_url' => '/auth/realms/Renku/protocol/openid-connect/token'
              },
              user_response_structure: {
                attributes: { email:'email', first_name:'given_name', last_name:'family_name', name:'name', nickname:'preferred_username' }, # if the nickname attribute of a user is called 'username'
                id_path: 'preferred_username'
              }
            },
            label: 'Renku Login'
          }
        ]
        gitlab_rails['gitlab_shell_ssh_port'] = 5022
        gitlab_rails['lfs_enabled'] = true
        gitlab_rails['lfs_storage_path'] = '/var/storage/lfs-objects'
        gitlab_rails['initial_root_password'] = 'root_password'
        gitlab_rails['initial_shared_runners_registration_token'] = '${GITLAB_RUNNERS_TOKEN}'
        # Add any other gitlab.rb configuration here, each on its own line
    ports:
      - '5022:22'
      - '5081:5081'
    volumes:
      - gitlab-config:/etc/gitlab
      - gitlab-logs:/var/log/gitlab
      - gitlab-data:/var/opt/gitlab
      - ./services/gitlab/Auto-DevOps.gitlab-ci.yml:/opt/gitlab/embedded/service/gitlab-rails/vendor/gitlab-ci-yml/Auto-DevOps.gitlab-ci.yml:ro
      - ./services/gitlab/lfs-data:/var/storage/lfs-objects # TODO: REMOVE ME
    depends_on:
      - db
    labels:
      traefik.enable: "true"
      traefik.frontend.rule: Host:gitlab.${PLATFORM_DOMAIN}
      traefik.port: '80'
    networks:
      default:
        aliases:
          - gitlab.${PLATFORM_DOMAIN}
      review:
        aliases:
          - gitlab.${PLATFORM_DOMAIN}

  gitlab-runner:
    image: ${DOCKER_PREFIX}gitlab-runner:${PLATFORM_VERSION}
    restart: always
    volumes:
      - gitlab-runner-data:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - default
      - review

  storage:
    image: ${DOCKER_PREFIX}renku-storage:${PLATFORM_VERSION}
    environment:
      # AUTHORIZATION_CLIENT_SECRET: $AUTHORIZATION_CLIENT_SECRET
      PLAY_APPLICATION_SECRET: $PLAY_APPLICATION_SECRET
      RENKU_SERVICES_AUTHORIZATION_URL: ${KEYCLOAK_URL}/auth/realms/Renku/protocol/openid-connect/auth
      STORAGE_BACKEND_LOCAL_ENABLED: "true"
      RENKU_ENDPOINT: ${RENKU_ENDPOINT}
      STORAGE_BACKEND_LOCALGIT_ENABLED: "true"
      STORAGE_BACKEND_GITLAB_ENABLED: "true"
      GITLAB_URL: ${GITLAB_URL}
      GITLAB_USER: "root"
      GITLAB_PASS: ${GITLAB_SUDO_TOKEN}
      RENKU_STORAGE_DEFAULT_LFS_BACKEND: "local"
    volumes:
      - ./services/storage/data:/data
    ports:
      - 9000
    restart: on-failure
    depends_on:
      - db
      - keycloak
    networks:
      - default
    labels:
      traefik.enable: "true"
      traefik.frontend.rule: PathPrefix:/api/storage

  apispec:
    build: ./services/apispec
    ports:
      - 5000
    labels:
      traefik.enable: "true"
      traefik.frontend.rule: Path:/api/swagger.json
    environment:
      API_ROOT_URL: http://reverse-proxy/api/
      SERVICES: storage
      WSGI_NUM_PROXIES: 1
  swagger:
    image: ${DOCKER_PREFIX}swagger-ui:latest
    ports:
      - 8080
    labels:
      traefik.enable: "true"
      traefik.frontend.rule: PathPrefixStrip:/admin/swagger
    environment:
      API_URL: ${RENKU_ENDPOINT}/api/swagger.json
      OAUTH2_REDIRECT_URL: ${RENKU_ENDPOINT}/admin/swagger/oauth2-redirect.html

  ui:
    image: ${DOCKER_PREFIX}renku-ui:${PLATFORM_VERSION}
    restart: always
    environment:
      BASE_URL: http://${PLATFORM_DOMAIN}
      GITLAB_URL: ${GITLAB_URL}
      JUPYTERHUB_URL: ${JUPYTERHUB_URL}
    labels:
      traefik.enable: "true"
      traefik.frontend.rule: "Host:${PLATFORM_DOMAIN}"
      traefik.frontend.passHostHeader: "false"
    networks:
      - default

  reverse-proxy:
    image: traefik
    command: --web --web.address=:81 \
      --docker --docker.watch --docker.domain=${PLATFORM_DOMAIN} \
      --debug --logLevel=INFO \
      --defaultentrypoints=http,https \
      --entrypoints='Name:http Address::80' \
      --entrypoints='Name:https Address::443 TLS:/ssl/test.crt,/ssl/test.key' \
      --entrypoints='Name:service Address::8080' \
      --docker.exposedbydefault=false
    # FIXME usage of self signed certs --entrypoints='Name:http Address::80 Redirect.EntryPoint:https' \
    ports:
      - 80:80
      - 443:443
      - 8080:8080
      - 81:81
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml
      - ./services/traefik/ssl/:/ssl/:ro
    networks:
      - default
      - review

  jupyterhub:
    image: ${DOCKER_PREFIX}jupyterhub:${PLATFORM_VERSION}
    build: services/jupyterhub
    command: jupyterhub --debug
    ports:
      - 8000
      - 8081
    environment:
      DEBUG: 1
      GITLAB_CLIENT_ID: jupyterhub
      GITLAB_CLIENT_SECRET: no-secret-needed
      GITLAB_HOST: ${GITLAB_URL}
      IMAGE_REGISTRY: gitlab.${PLATFORM_DOMAIN}:5081
      JUPYTERHUB_CRYPT_KEY: ${JUPYTERHUB_CRYPT_KEY}
      JUPYTERHUB_NOTEBOOK_DIR: /repo
      JUPYTERHUB_NOTEBOOK_IMAGE: ${DOCKER_PREFIX}singleuser:${PLATFORM_VERSION}
      JUPYTERHUB_RENKU_NOTEBOOKS_SERVICE_TOKEN: ${JUPYTERHUB_RENKU_NOTEBOOKS_SERVICE_TOKEN}
      JUPYTERHUB_SPAWNER_CLASS: spawners.RenkuDockerSpawner
      KEYCLOAK_URL: ${KEYCLOAK_URL}
      OAUTH2_AUTHORIZE_URL: ${KEYCLOAK_URL}/auth/realms/Renku/protocol/openid-connect/auth
      OAUTH2_TOKEN_URL: ${KEYCLOAK_URL}/auth/realms/Renku/protocol/openid-connect/token
      PLATFORM_DOMAIN: ${PLATFORM_DOMAIN}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./services/jupyterhub/jupyterhub_config.py:/srv/jupyterhub/jupyterhub_config.py:ro
      - ./services/jupyterhub/project_service.py:/srv/jupyterhub/project_service.py:ro
      - ./services/jupyterhub/spawners.py:/srv/jupyterhub/spawners.py:ro
    labels:
      traefik.enable: "true"
      traefik.port: '8000'
      traefik.frontend.rule: "Host:jupyterhub.${PLATFORM_DOMAIN}"
    networks:
      default:
        aliases:
          - jupyterhub.${PLATFORM_DOMAIN}
      review:
        aliases:
          - jupyterhub.${PLATFORM_DOMAIN}

  notebooks:
    build: services/notebooks
    environment:
      FLASK_DEBUG: 1
      OAUTHLIB_INSECURE_TRANSPORT: 1
      JUPYTERHUB_API_TOKEN: ${JUPYTERHUB_RENKU_NOTEBOOKS_SERVICE_TOKEN}
      JUPYTERHUB_API_URL: http://jupyterhub:8000/hub/api
      JUPYTERHUB_SERVICE_PREFIX: /services/notebooks/
networks:
  review:
    external: true
