dependencies:
- name: renku-ui
  alias: ui
  version: "0.2.0"
  repository: "https://swissdatasciencecenter.github.io/helm-charts/"
- name: renku-notebooks
  alias: notebooks
  repository: "https://swissdatasciencecenter.github.io/helm-charts/"
  version: "0.2.0"
- name: renku-gateway
  alias: gateway
  repository: "https://swissdatasciencecenter.github.io/helm-charts/"
  version: "0.2.0"
- name: gitlab
  version: "0.2.0"
  repository: "https://swissdatasciencecenter.github.io/helm-charts/"
  condition: gitlab.enabled
- name: postgresql
  version: 0.14.4
  repository: "@stable"
- name: redis
  version: 3.7.2
  repository: "@stable"
  condition: gitlab.enabled
- name: keycloak
  version: 3.2.0
  repository: "@stable"
  condition: keycloak.enabled
- name: minio
  version: 1.6.0
  repository: "@stable"
  condition: minio.enabled
