apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "renku.search.searchApi.fullname" . }}
  labels:
    app: {{ template "renku.search.searchApi.name" . }}
    chart: {{ template "renku.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.search.searchApi.replicas }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ template "renku.search.searchApi.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "renku.search.searchApi.name" . }}
        release: {{ .Release.Name }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      automountServiceAccountToken: {{ .Values.global.debug }}
      containers:
        - name: search-api
          image: "{{ .Values.search.searchApi.image.repository }}:{{ .Values.search.searchApi.image.tag }}"
          imagePullPolicy: {{ .Values.search.searchApi.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          env:
            - name: RS_SOLR_URL
              value: "http://{{ template "solr.fullname" . }}:{{ .Values.global.solr.port }}"
            - name: RS_SOLR_CORE
              value: {{ first .Values.solr.coreNames }}
            - name: RS_SOLR_USER
              value: {{ default "admin" .Values.solr.auth.adminUsername | quote }}
            - name: RS_SOLR_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ template "solr.fullname" . }}
                  key: solr-password
            - name: RS_SOLR_DEFAULT_COMMIT_WITHIN
              value: "500ms"
            - name: RS_SOLR_LOG_MESSAGE_BODIES
              value: "false"
            - name: "RS_JWT_ALLOWED_ISSUER_URL_PATTERNS"
              value: "{{ include "renku.keycloakUrl" . }}*/*"
            - name: JAVA_OPTS
              value: "-Xmx{{ .Values.search.searchApi.jvmXmx }} -XX:+UseZGC -XX:+ZGenerational"
          ports:
            - name: http-search-api
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /ping
              port: http-search-api
          readinessProbe:
            httpGet:
              path: /ping
              port: http-search-api
          resources:
            {{- toYaml .Values.search.searchApi.resources | nindent 12 }}
          volumeMounts:
            {{- include "certificates.volumeMounts.javaCertsGeneral" . | nindent 12 }}
      volumes:
        {{- include "certificates.volumes" . | nindent 8 }}
  {{- with .Values.nodeSelector }}
nodeSelector:
  {{ toYaml . | indent 8 }}
  {{- end }}
  {{- with .Values.affinity }}
affinity:
  {{ toYaml . | indent 8 }}
  {{- end }}
  {{- with .Values.tolerations }}
tolerations:
  {{ toYaml . | indent 8 }}
  {{- end }}
