# Default values for gitlab.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: gitlab/gitlab-ce
  tag: 11.3.6-ce.0
  pullPolicy: IfNotPresent

ssh:
  externalPort: 22
  nodePortService:
    enabled: false
    nodePort: 30022

## LFS objects in remote object storage
## Follows: https://docs.gitlab.com/ce/workflow/lfs/lfs_administration.html#storing-lfs-objects-in-remote-object-storage
lfsObjects:
  enabled: false
  bucketName: lfs-objects
  directUpload: false
  backgroundUpload: true
  proxyDownload: false
  # connection: |-
  #   {
  #     'provider' => 'AWS',
  #     'region' => 'eu-central-1',
  #     'aws_access_key_id' => '1ABCD2EFGHI34JKLM567N',
  #     'aws_secret_access_key' => 'abcdefhijklmnopQRSTUVwxyz0123456789ABCDE',
  #     # The below options configure an S3 compatible host instead of AWS
  #     'host' => 'localhost',
  #     'endpoint' => 'http://127.0.0.1:9000',
  #     'path_style' => true
  #   }

service:
  type: ClusterIP
  port: 80
  metrics:
    enabled: true
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/path: /gitlab/-/metrics

persistence:
  enabled: true

  ## A manually managed Persistent Volume and Claim
  ## Requires persistence.enabled: true
  ## If defined, PVC must be created manually before volume will be bound
  # existingClaim:

  # storageClass: "-"
  accessMode: ReadWriteOnce
  size: 30Gi

  gitlab_data:
    subPath: data
    mountPath: /var/opt/gitlab
  gitlab_config:
    subPath: config
    mountPath: /etc/gitlab
  gitlab_logs:
    subPath: logs
    mountPath: /var/log/gitlab


registry:
  enabled: false
  exposedAs: Ingress
  # exposedAs: NodePort
  backendHealthcheck: true
  # storage: |-
  #   {
  #     's3' => {
  #       'accesskey' => 's3-access-key',
  #       'secretkey' => 's3-secret-key-for-access-key',
  #       'bucket' => 'your-s3-bucket',
  #       'region' => 'your-s3-region'
  #     }
  #   }

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

redis:

  nameOverride: gl-redis

  cluster:
    enabled: false

  usePassword: false

  master:
    persistence:
      enabled: false

  networkPolicy:
    enabled: true
    allowExternal: false
