apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "gitlab.fullname" . }}
  labels:
    app: {{ template "gitlab.name" . }}
    chart: {{ template "gitlab.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ template "gitlab.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "gitlab.name" . }}
        release: {{ .Release.Name }}
        {{ template "redis.fullname" . }}-client: "true"
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: POSTGRES_DATABASE
          value: {{ .Values.global.gitlab.postgresDatabase }}
        - name: POSTGRES_USER
          value: {{ .Values.global.gitlab.postgresUser }}
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "gitlab.fullname" . }}
              key: postgres-password
        - name: GITLAB_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ template "gitlab.fullname" . }}
              key: gitlab-client-secret
        - name: GITLAB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "gitlab.fullname" . }}
              key: gitlab-password
        - name: RENKU_DOMAIN
          value: {{ .Values.global.renku.domain }}
        - name: GITLAB_SHARED_RUNNERS_REGISTRATION_TOKEN
          valueFrom:
            secretKeyRef:
              name: {{ template "gitlab.fullname" . }}
              key: shared-runners-registration-token
        ports:
        - name: ssh
          containerPort: 22
        - name: http
          containerPort: 80
        - name: registry
          containerPort: 8105
        livenessProbe:
          httpGet:
            path: {{ .Values.global.gitlab.urlPrefix }}help
            port: http
          # This pod takes a very long time to start up. Be cautious when
          # lowering this value to avoid Pod death during startup.
          initialDelaySeconds: 600
          timeoutSeconds: 15
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 10
        readinessProbe:
          httpGet:
            path: {{ .Values.global.gitlab.urlPrefix }}help
            port: http
          initialDelaySeconds: 60
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        resources:
{{ toYaml .Values.resources | indent 10 }}
        volumeMounts:
          - name: gitlab-persistence
            mountPath: {{ .Values.persistence.gitlab_data.mountPath }}
            subPath: {{ .Values.persistence.gitlab_data.subPath }}
          - name: gitlab-persistence
            mountPath: {{ .Values.persistence.gitlab_config.mountPath }}
            subPath: {{ .Values.persistence.gitlab_config.subPath }}
          - name: gitlab-persistence
            mountPath: {{ .Values.persistence.gitlab_logs.mountPath }}
            subPath: {{ .Values.persistence.gitlab_logs.subPath }}
          - name: config
            mountPath: /etc/gitlab/gitlab.rb
            subPath: gitlab.rb
      volumes:
        - name: gitlab-persistence
        {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (include "gitlab.fullname" .) }}
        {{- else }}
          emptyDir: {}
        {{- end }}
        - name: config
          configMap:
            name: {{ template "gitlab.fullname" . }}-config

    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
