---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "storage.fullname" . }}
  labels:
    app: {{ template "storage.name" . }}
    chart: {{ template "storage.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  application-secret: {{ .Values.appSecret | b64enc | quote }}
  postgres-password: {{ .Values.global.storage.postgresPassword | b64enc | quote }}
