{{- if .Values.keycloakx.alerts.alertmanager.enabled }}
---

{{- $alertmanagerClientSecret := .Values.keycloakx.alerts.alertmanager.clientSecret | default (randAlphaNum 64) | b64enc | quote }}

{{- $renkuFullname := include "renku.fullname" . -}}
{{- $secretName := cat $renkuFullname "-alertmanager-webhook" | nospace }}

{{- if not .Values.keycloakx.alerts.alertmanager.clientSecret -}}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace $secretName) }}
{{- if $secret }}
{{- $alertmanagerClientSecret = index $secret.data "alertmanagerClientSecret" }}
{{- end -}}
{{- end -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    app: {{ template "renku.name" . }}
    chart: {{ template "renku.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade,pre-rollback"
type: Opaque
data:
  # A secret for the "alertmanager-webhook" OIDC client in Keycloak
  alertmanagerClientSecret: {{ $alertmanagerClientSecret }}
{{- end }}
